# O-Cloud Custom Resource Definition
# Nephio R5 / O-RAN L Release compatible
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: oclouds.ocloud.oran.io
  annotations:
    nephio.org/version: "r5"
    oran.org/release: "l-release"
spec:
  group: ocloud.oran.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              smo:
                type: object
                properties:
                  enabled:
                    type: boolean
                  endpoint:
                    type: string
                  authType:
                    type: string
                  capabilities:
                    type: array
                    items:
                      type: string
                  aimlEnabled:
                    type: boolean
              resourcePools:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    type:
                      type: string
                    location:
                      type: string
                    capacity:
                      type: object
                      properties:
                        cpu:
                          type: string
                        memory:
                          type: string
                        storage:
                          type: string
                        network:
                          type: string
                    labels:
                      type: object
                      additionalProperties:
                        type: string
              o2Interface:
                type: object
                properties:
                  enabled:
                    type: boolean
                  version:
                    type: string
                  endpoints:
                    type: array
                    items:
                      type: string
                  authEnabled:
                    type: boolean
              infrastructureType:
                type: string
              regions:
                type: array
                items:
                  type: string
          status:
            type: object
            properties:
              phase:
                type: string
              message:
                type: string
              smoStatus:
                type: string
              o2Status:
                type: string
              lastReconciled:
                type: string
              resourceInventory:
                type: object
                properties:
                  totalCpu:
                    type: integer
                  availableCpu:
                    type: integer
                  totalMemory:
                    type: integer
                  availableMemory:
                    type: integer
                  totalStorage:
                    type: integer
                  availableStorage:
                    type: integer
                  resourceTypes:
                    type: object
                    additionalProperties:
                      type: integer
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    lastTransitionTime:
                      type: string
                    reason:
                      type: string
                    message:
                      type: string
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Phase
      type: string
      jsonPath: .status.phase
    - name: SMO
      type: string
      jsonPath: .status.smoStatus
    - name: O2
      type: string
      jsonPath: .status.o2Status
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: oclouds
    singular: ocloud
    kind: OCloud
    shortNames:
    - oc
---
# Resource Pool CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: resourcepools.ocloud.oran.io
spec:
  group: ocloud.oran.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              type:
                type: string
                enum: ["compute", "network", "storage", "accelerator"]
              location:
                type: string
              capacity:
                type: object
                properties:
                  cpu:
                    type: string
                  memory:
                    type: string
                  storage:
                    type: string
                  network:
                    type: string
                  gpu:
                    type: integer
              nodeSelector:
                type: object
                additionalProperties:
                  type: string
              tolerations:
                type: array
                items:
                  type: object
                  properties:
                    key:
                      type: string
                    operator:
                      type: string
                    value:
                      type: string
                    effect:
                      type: string
          status:
            type: object
            properties:
              phase:
                type: string
              allocated:
                type: object
                properties:
                  cpu:
                    type: string
                  memory:
                    type: string
                  storage:
                    type: string
              available:
                type: object
                properties:
                  cpu:
                    type: string
                  memory:
                    type: string
                  storage:
                    type: string
              utilizationPercentage:
                type: object
                properties:
                  cpu:
                    type: number
                  memory:
                    type: number
                  storage:
                    type: number
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Type
      type: string
      jsonPath: .spec.type
    - name: Location
      type: string
      jsonPath: .spec.location
    - name: CPU Util
      type: number
      jsonPath: .status.utilizationPercentage.cpu
    - name: Memory Util
      type: number
      jsonPath: .status.utilizationPercentage.memory
    - name: Phase
      type: string
      jsonPath: .status.phase
  scope: Namespaced
  names:
    plural: resourcepools
    singular: resourcepool
    kind: ResourcePool
    shortNames:
    - rp