apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: ric-platform-mtls
  namespace: near-rt-ric
spec:
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: ric-access-control
  namespace: near-rt-ric
spec:
  rules:
  - from:
    - source:
        namespaces: ["near-rt-ric", "non-rt-ric"]
  - to:
    - operation:
        methods: ["GET", "POST", "PUT", "DELETE"]
