# Prometheus 3.5 LTS Configuration for Nephio R5/O-RAN L Release
# Updated: 2025-01-19
# Breaking changes from 2.x: https://prometheus.io/docs/prometheus/3.0/migration/
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
  labels:
    app: prometheus
    version: "3.5.0"
    component: monitoring
data:
  prometheus.yml: |
    # Prometheus 3.5 LTS Configuration
    # Major changes from 2.x:
    # - Native histograms enabled by default
    # - UTF-8 metric names fully supported
    # - New TSDB format with better compression
    # - Changed remote_write behavior
    
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      external_labels:
        cluster: 'nephio-r5'
        environment: 'production'
        prometheus_version: '3.5.0'
    
    # Prometheus 3.x feature flags
    # Note: Some flags changed from 2.x
    enable_features:
      - native-histograms        # Now stable in 3.x
      - utf8-metric-names        # Fully supported in 3.x
      - prometheus-agent-mode    # New in 3.x for edge deployments
      - memory-snapshot-on-shutdown # Improved in 3.x
      - new-service-discovery-manager # Enhanced in 3.x
    
    # Runtime configuration (3.x specific)
    runtime:
      gogc: 75  # Adjusted for 3.x memory management
    
    # Storage configuration (enhanced in 3.x)
    storage:
      tsdb:
        path: /prometheus
        retention: 15d
        # New in 3.x: improved compression
        wal_compression: snappy
        # New in 3.x: native histogram settings
        enable_native_histograms: true
        max_exemplars: 100000
    
    # Alertmanager configuration
    alerting:
      alertmanagers:
        - static_configs:
            - targets:
                - alertmanager:9093
          # New in 3.x: timeout configuration
          timeout: 10s
          api_version: v2
    
    # Rule files
    rule_files:
      - "/etc/prometheus/rules/*.yml"
    
    scrape_configs:
      # Self-monitoring
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
        metric_relabel_configs:
          # New in 3.x: improved relabeling performance
          - source_labels: [__name__]
            regex: 'prometheus_.*'
            action: keep
      
      # Grafana 12.x metrics
      - job_name: 'grafana'
        static_configs:
          - targets: ['grafana:3000']
        metrics_path: '/metrics'
      
      # ArgoCD metrics (primary in R5)
      - job_name: 'argocd-metrics'
        static_configs:
          - targets: ['argocd-metrics:8082']
        metric_relabel_configs:
          - source_labels: [__name__]
            regex: 'argocd_.*'
            action: keep
      
      # Nephio R5 controllers with Go 1.24.6
      - job_name: 'nephio-controllers'
        static_configs:
          - targets: 
            - 'nephio-controller:8080'
            - 'porch-server:8080'
        metric_relabel_configs:
          - source_labels: [__name__]
            regex: 'go_.*|process_.*|nephio_.*'
            action: keep
      
      # O-RAN L Release components
      - job_name: 'oran-l-release'
        static_configs:
          - targets: 
            - 'du-l-release:8080'
            - 'cu-l-release:8080'
            - 'ric-l-release:8080'
            - 'smo-l-release:8080'
        metric_relabel_configs:
          - source_labels: [__name__]
            regex: 'oran_.*|ai_ml_.*|ves_.*'
            action: keep
      
      # OCloud infrastructure
      - job_name: 'ocloud-metrics'
        static_configs:
          - targets: ['ocloud-controller:8080']
        metric_relabel_configs:
          - source_labels: [__name__]
            regex: 'ocloud_.*|baremetal_.*|metal3_.*'
            action: keep
      
      # Kubernetes components
      - job_name: 'kubernetes-apiservers'
        kubernetes_sd_configs:
          - role: endpoints
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
            action: keep
            regex: default;kubernetes;https
      
      # Node exporter
      - job_name: 'node-exporter'
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - source_labels: [__address__]
            regex: '(.*):10250'
            replacement: '${1}:9100'
            target_label: __address__
    
    # Remote write configuration (changed in 3.x)
    remote_write:
      - url: "http://victoria-metrics:8428/api/v1/write"
        # New in 3.x: protocol version
        remote_write_protocol: "2.0"
        queue_config:
          capacity: 10000
          max_shards: 100
          min_shards: 1
          max_samples_per_send: 5000
          batch_send_deadline: 5s
          # New in 3.x: retry on rate limit
          retry_on_rate_limit: true
        metadata_config:
          send: true
          send_interval: 1m
          # New in 3.x: max samples per metadata send
          max_samples_per_send: 500
    
    # Remote read configuration
    remote_read:
      - url: "http://victoria-metrics:8428/api/v1/read"
        read_recent: true
        # New in 3.x: filter external labels
        filter_external_labels: false

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: monitoring
data:
  recording_rules.yml: |
    groups:
      - name: nephio_r5_3x_rules
        interval: 30s
        rules:
          # Native histogram example (3.x feature)
          - record: http_request_duration:histogram
            expr: |
              histogram_quantile(0.99,
                sum(rate(http_request_duration_seconds[5m])) by (le, method, status)
              )
          
          # UTF-8 metric names (3.x feature)
          - record: "nephio:パッケージ展開成功率"  # Japanese for package deployment success rate
            expr: |
              sum(rate(nephio_package_deployed_total[1h])) /
              sum(rate(nephio_package_attempted_total[1h])) * 100
          
          # Memory-efficient aggregation (improved in 3.x)
          - record: cluster:cpu_usage:ratio
            expr: |
              1 - avg(rate(node_cpu_seconds_total{mode="idle"}[5m]))
  
  alerting_rules.yml: |
    groups:
      - name: prometheus_3x_alerts
        rules:
          - alert: PrometheusVersionMismatch
            expr: prometheus_build_info{version!~"3\\.5\\..*"}
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "Prometheus version is not 3.5.x LTS"
              description: "Instance {{ $labels.instance }} is running version {{ $labels.version }}, expected 3.5.x LTS"
          
          - alert: HighMemoryUsage
            expr: |
              (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) > 0.9
            for: 5m
            labels:
              severity: critical
            annotations:
              summary: "High memory usage detected"
              description: "Memory usage is above 90% on {{ $labels.instance }}"