name: deploy-complete
description: Full O-RAN deployment workflow with Nephio R5 and L Release
version: 1.0.0
stages:
  - name: infrastructure
    agent: nephio-infrastructure-agent
    description: Provision O-Cloud infrastructure and Kubernetes clusters
    tasks:
      - Setup management cluster with Nephio R5
      - Deploy workload clusters with ArgoCD
      - Configure CNI and storage
      - Enable baremetal provisioning
    expected_outputs:
      - Cluster endpoints
      - ArgoCD access details
      - Infrastructure metrics
    
  - name: dependencies
    agent: oran-nephio-dep-doctor-agent
    description: Validate and resolve all dependency requirements
    tasks:
      - Check Go 1.24.6 compatibility
      - Verify O-RAN L Release components
      - Resolve missing packages
      - Validate FIPS compliance
    expected_outputs:
      - Dependency report
      - Compatibility matrix
      - Resolution actions
    
  - name: configuration
    agent: configuration-management-agent
    description: Apply configurations and GitOps setup
    tasks:
      - Deploy Kpt packages
      - Configure YANG models
      - Setup ArgoCD applications
      - Apply security policies
    expected_outputs:
      - Configuration status
      - GitOps sync state
      - Policy compliance report
    
  - name: network-functions
    agent: oran-network-functions-agent
    description: Deploy O-RAN network functions
    tasks:
      - Deploy Near-RT RIC
      - Deploy Non-RT RIC
      - Install xApps/rApps
      - Configure O-CU/O-DU/O-RU
    expected_outputs:
      - NF deployment status
      - Service endpoints
      - Health check results
    
  - name: monitoring
    agent: monitoring-analytics-agent
    description: Setup observability and analytics
    tasks:
      - Deploy Prometheus/Grafana
      - Configure VES collectors
      - Setup AI/ML analytics
      - Enable NWDAF integration
    expected_outputs:
      - Monitoring dashboards
      - Alert configurations
      - Metrics collection status
    
  - name: optimization
    agent: performance-optimization-agent
    description: Optimize performance and resources
    tasks:
      - Baseline performance metrics
      - Apply AI/ML optimization
      - Configure auto-scaling
      - Enable energy efficiency
    expected_outputs:
      - Performance report
      - Optimization recommendations
      - Resource utilization metrics

completion_actions:
  - Generate deployment report
  - Archive configuration artifacts
  - Create rollback snapshot
  - Send notification

rollback_strategy:
  enabled: true
  checkpoint_after_each_stage: true
  max_rollback_attempts: 3
