name: troubleshoot
description: Issue resolution workflow for O-RAN/Nephio environments
version: 1.0.0
stages:
  - name: diagnosis
    agent: monitoring-analytics-agent
    description: Collect metrics and identify issues
    tasks:
      - Gather system metrics
      - Check alert status
      - Analyze logs and events
      - Identify anomalies
    expected_outputs:
      - Issue summary
      - Affected components
      - Timeline of events
      - Initial assessment
    
  - name: root-cause
    agent: oran-nephio-dep-doctor-agent
    description: Perform root cause analysis
    tasks:
      - Analyze dependency chains
      - Check version compatibility
      - Review configuration drift
      - Identify failure patterns
    expected_outputs:
      - Root cause report
      - Dependency issues
      - Configuration problems
      - Recommended fixes
    
  - name: remediation
    agent: configuration-management-agent
    description: Apply fixes and remediation
    tasks:
      - Apply configuration fixes
      - Update dependencies
      - Restart affected services
      - Rollback if necessary
    expected_outputs:
      - Applied fixes list
      - Service restart status
      - Configuration changes
      - Rollback actions
    
  - name: verification
    agent: testing-validation-agent
    description: Verify fixes and system health
    tasks:
      - Run health checks
      - Execute validation tests
      - Verify service connectivity
      - Check performance metrics
    expected_outputs:
      - Test results
      - Health status
      - Performance comparison
      - Validation report

completion_actions:
  - Generate incident report
  - Update runbook documentation
  - Create preventive measures
  - Send resolution notification

escalation_policy:
  max_attempts_per_stage: 3
  timeout_minutes: 30
  fallback_to_manual: true
