name: upgrade
description: System upgrade workflow for Nephio R5 and O-RAN L Release
version: 1.0.0
stages:
  - name: pre-check
    agent: testing-validation-agent
    description: Pre-upgrade validation and checks
    tasks:
      - Verify current system state
      - Check upgrade prerequisites
      - Validate backup availability
      - Test rollback procedures
    expected_outputs:
      - System health report
      - Prerequisites status
      - Backup verification
      - Rollback readiness
    
  - name: backup
    agent: configuration-management-agent
    description: Create comprehensive system backup
    tasks:
      - Backup configurations
      - Snapshot persistent data
      - Export GitOps state
      - Archive current packages
    expected_outputs:
      - Backup manifest
      - Snapshot IDs
      - GitOps export
      - Package archives
    
  - name: upgrade-infra
    agent: nephio-infrastructure-agent
    description: Upgrade infrastructure components
    tasks:
      - Upgrade Kubernetes clusters
      - Update Nephio controllers
      - Upgrade ArgoCD
      - Update CNI and storage
    expected_outputs:
      - Upgrade status
      - Component versions
      - Migration logs
      - Health checks
    
  - name: upgrade-nf
    agent: oran-network-functions-agent
    description: Upgrade network functions
    tasks:
      - Upgrade RIC platforms
      - Update xApps/rApps
      - Upgrade O-CU/O-DU/O-RU
      - Migrate configurations
    expected_outputs:
      - NF upgrade status
      - Service continuity report
      - Configuration migration
      - Compatibility matrix
    
  - name: validate
    agent: testing-validation-agent
    description: Post-upgrade validation
    tasks:
      - Run integration tests
      - Verify service health
      - Check performance metrics
      - Validate configurations
    expected_outputs:
      - Test results
      - Health status
      - Performance comparison
      - Validation report

completion_actions:
  - Generate upgrade report
  - Clean up old resources
  - Update documentation
  - Send completion notification

rollback_triggers:
  - Critical service failure
  - Performance degradation >20%
  - Security vulnerability detected
  - Integration test failure

upgrade_strategy:
  type: rolling
  canary_percentage: 10
  drain_timeout_seconds: 300
  max_unavailable: 1
