name: validate
description: Security and compliance validation workflow
version: 1.0.0
stages:
  - name: security-scan
    agent: security-compliance-agent
    description: Perform comprehensive security scanning
    tasks:
      - Scan container images
      - Check SBOM compliance
      - Verify certificates
      - Audit RBAC policies
      - Check FIPS compliance
    expected_outputs:
      - Vulnerability report
      - SBOM validation
      - Certificate status
      - Policy compliance
      - FIPS mode verification
    
  - name: dependency-check
    agent: oran-nephio-dep-doctor-agent
    description: Validate all dependencies
    tasks:
      - Check Go 1.24.6 compatibility (with Go Cryptographic Module v1.0.0)
      - Verify package versions
      - Scan for CVEs
      - Check license compliance
    expected_outputs:
      - Dependency tree
      - Version matrix
      - CVE report
      - License summary
    
  - name: performance-baseline
    agent: performance-optimization-agent
    description: Establish performance baselines
    tasks:
      - Measure latency metrics
      - Check throughput capacity
      - Monitor resource usage
      - Validate SLA compliance
    expected_outputs:
      - Performance metrics
      - Baseline report
      - Resource utilization
      - SLA validation

completion_actions:
  - Generate compliance report
  - Archive scan results
  - Update security dashboard
  - Send validation summary

compliance_standards:
  - O-RAN WG11 Security
  - FIPS 140-3
  - CIS Kubernetes Benchmark
  - NIST Cybersecurity Framework
