# Nephio-O-RAN Claude Agent Configuration
# This file manages cost data and model assignments for all agents

agent_models:
  nephio-infrastructure-agent:
    model: haiku
    avg_tokens_per_task: 500
    max_acceptable: 1000
    cost_per_1k_tokens: 0.0015
    description: "Fast infrastructure operations and resource management"
    
  oran-network-functions-agent:
    model: sonnet
    avg_tokens_per_task: 1500
    max_acceptable: 3000
    cost_per_1k_tokens: 0.015
    description: "Network function deployment and management"
    
  security-compliance-agent:
    model: opus
    avg_tokens_per_task: 3000
    max_acceptable: 6000
    cost_per_1k_tokens: 0.075
    description: "Security analysis and compliance validation"
    
  performance-optimization-agent:
    model: opus
    avg_tokens_per_task: 2800
    max_acceptable: 5500
    cost_per_1k_tokens: 0.075
    description: "Performance tuning and optimization"
    
  nephio-oran-orchestrator-agent:
    model: opus
    avg_tokens_per_task: 3500
    max_acceptable: 7000
    cost_per_1k_tokens: 0.075
    description: "Complex orchestration and integration"
    
  configuration-management-agent:
    model: sonnet
    avg_tokens_per_task: 1200
    max_acceptable: 2500
    cost_per_1k_tokens: 0.015
    description: "Configuration automation and management"
    
  monitoring-analytics-agent:
    model: sonnet
    avg_tokens_per_task: 1800
    max_acceptable: 3500
    cost_per_1k_tokens: 0.015
    description: "Observability and analytics setup"
    
  data-analytics-agent:
    model: haiku
    avg_tokens_per_task: 600
    max_acceptable: 1200
    cost_per_1k_tokens: 0.0015
    description: "Data processing and basic analytics"

# Model pricing (can be updated as Claude pricing changes)
model_pricing:
  haiku: 0.0015
  sonnet: 0.015
  opus: 0.075

# Global settings
settings:
  csv_log_file: "token_usage_log.csv"
  max_efficiency_threshold: 2.0  # Warning if usage exceeds 2x average
  cost_alert_threshold: 0.10     # Alert if single task costs > $0.10