apiVersion: v1
kind: Namespace
metadata:
  name: oran-network-functions
  labels:
    name: oran-network-functions
    istio-injection: enabled
    nephio.org/managed: "true"
    nephio.org/version: r5
    security.nephio.org/validated: "true"
  annotations:
    nephio.org/description: "O-RAN Network Functions namespace with security and service mesh"
    security.nephio.org/l-release-compliant: "true"
    policy.open-policy-agent.org/policy: oran-security-policy
---
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: default
  namespace: oran-network-functions
spec:
  egress:
  - hosts:
    - "./*"
    - "istio-system/*"
    - "monitoring/*"
    - "kube-system/*"
  ingress:
  - port:
      number: 38472
      name: f1-interface
      protocol: HTTP
    defaultEndpoint: 127.0.0.1:38472
  - port:
      number: 38465
      name: e1-interface
      protocol: HTTP
    defaultEndpoint: 127.0.0.1:38465
  - port:
      number: 38412
      name: ngap-interface
      protocol: HTTP
    defaultEndpoint: 127.0.0.1:38412
  - port:
      number: 38473
      name: f1-client
      protocol: HTTP
    defaultEndpoint: 127.0.0.1:38473
  - port:
      number: 7777
      name: ofh-cplane
      protocol: HTTP
    defaultEndpoint: 127.0.0.1:7777
  - port:
      number: 7778
      name: ofh-uplane
      protocol: HTTP
    defaultEndpoint: 127.0.0.1:7778
  - port:
      number: 7779
      name: ofh-splane
      protocol: HTTP
    defaultEndpoint: 127.0.0.1:7779
  - port:
      number: 7780
      name: ofh-mplane
      protocol: HTTP
    defaultEndpoint: 127.0.0.1:7780
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: oran-network-functions
spec:
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: oran-nf-default-deny
  namespace: oran-network-functions
spec:
  # Default deny all - specific policies will allow traffic
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: oran-nf-allow-internal
  namespace: oran-network-functions
spec:
  rules:
  - from:
    - source:
        namespaces: ["oran-network-functions"]
  - from:
    - source:
        namespaces: ["istio-system"]
        principals: ["cluster.local/ns/istio-system/sa/istio-proxy-sa"]
  - from:
    - source:
        namespaces: ["monitoring"]
        principals: ["cluster.local/ns/monitoring/sa/prometheus"]