apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-ric-config
  namespace: near-rt-ric
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    rule_files:
    - "/etc/prometheus/rules/*.yml"
    
    scrape_configs:
    - job_name: 'ric-platform'
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names: ['near-rt-ric']
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
        
    - job_name: 'xapps'
      kubernetes_sd_configs:
      - role: service
        namespaces:
          names: ['near-rt-ric']
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_component]
        action: keep
        regex: xapp
