name: CI Complete - Fixed

on:
  workflow_run:
    workflows: ["CI - Build, Test & Validate - Fixed"]
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  pull-requests: write

jobs:
  ci-status:
    name: CI Status Check
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'cancelled'
    steps:
      - name: Check CI workflow status
        id: ci-status
        run: |
          CONCLUSION="${{ github.event.workflow_run.conclusion }}"
          echo "CI workflow conclusion: $CONCLUSION"
          echo "conclusion=$CONCLUSION" >> $GITHUB_OUTPUT
          
          if [[ "$CONCLUSION" == "success" ]]; then
            echo "status=✅ Success" >> $GITHUB_OUTPUT
            echo "message=All CI checks passed successfully" >> $GITHUB_OUTPUT
          elif [[ "$CONCLUSION" == "failure" ]]; then
            echo "status=❌ Failed" >> $GITHUB_OUTPUT
            echo "message=CI checks failed - please review the logs" >> $GITHUB_OUTPUT
          else
            echo "status=⚠️ $CONCLUSION" >> $GITHUB_OUTPUT
            echo "message=CI workflow completed with status: $CONCLUSION" >> $GITHUB_OUTPUT
          fi

      - name: Generate CI summary
        run: |
          echo "## 🔄 CI Complete Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Workflow:** ${{ github.event.workflow_run.name }}" >> $GITHUB_STEP_SUMMARY
          echo "**Status:** ${{ steps.ci-status.outputs.status }}" >> $GITHUB_STEP_SUMMARY
          echo "**Branch:** ${{ github.event.workflow_run.head_branch }}" >> $GITHUB_STEP_SUMMARY
          echo "**Commit:** ${{ github.event.workflow_run.head_sha }}" >> $GITHUB_STEP_SUMMARY
          echo "**Run ID:** ${{ github.event.workflow_run.id }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Message:** ${{ steps.ci-status.outputs.message }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "[View CI Run](${{ github.event.workflow_run.html_url }})" >> $GITHUB_STEP_SUMMARY

      - name: Comment on PR (if applicable)
        if: github.event.workflow_run.event == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const conclusion = '${{ github.event.workflow_run.conclusion }}';
            const workflowName = '${{ github.event.workflow_run.name }}';
            const runId = '${{ github.event.workflow_run.id }}';
            const runUrl = '${{ github.event.workflow_run.html_url }}';
            
            let status, message;
            if (conclusion === 'success') {
              status = '✅ Success';
              message = 'All CI checks passed successfully';
            } else if (conclusion === 'failure') {
              status = '❌ Failed';
              message = 'CI checks failed - please review the logs';
            } else {
              status = `⚠️ ${conclusion}`;
              message = `CI workflow completed with status: ${conclusion}`;
            }
            
            const comment = `## 🔄 CI Complete
            
            **Status:** ${status}
            **Message:** ${message}
            
            [View CI Run](${runUrl})
            `;
            
            // Try to find the PR number from the workflow run
            try {
              const pulls = await github.rest.pulls.list({
                owner,
                repo,
                state: 'open',
                head: `${owner}:${{ github.event.workflow_run.head_branch }}`
              });
              
              if (pulls.data.length > 0) {
                const prNumber = pulls.data[0].number;
                await github.rest.issues.createComment({
                  owner,
                  repo,
                  issue_number: prNumber,
                  body: comment
                });
                console.log(`Posted comment to PR #${prNumber}`);
              }
            } catch (error) {
              console.log('Could not post PR comment:', error.message);
            }

  # Set final status
  final-status:
    name: Final Status
    runs-on: ubuntu-latest
    needs: ci-status
    if: always()
    steps:
      - name: Set final status
        run: |
          CONCLUSION="${{ github.event.workflow_run.conclusion }}"
          echo "Final CI status: $CONCLUSION"
          
          if [[ "$CONCLUSION" == "success" ]]; then
            echo "✅ CI pipeline completed successfully"
            echo "All checks passed - ready for deployment"
          elif [[ "$CONCLUSION" == "failure" ]]; then
            echo "❌ CI pipeline failed"
            echo "Please review and fix the failing checks"
            exit 1
          else
            echo "⚠️ CI pipeline completed with status: $CONCLUSION"
            echo "Review the workflow results before proceeding"
          fi