name: Test Coverage Gate

on:
  push:
    branches: [ main, develop, 'feat/*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  # Go test coverage is disabled as all Go code has been removed from the repository
  # The repository now focuses on documentation and Claude agents
  test-coverage-placeholder:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Skip Go tests - No Go code in repository
      run: |
        echo "✅ Go test coverage skipped - repository contains no Go code"
        echo "This workflow is preserved for future use if Go code is reintroduced"
        echo "Current repository focus: Documentation site and Claude agents"
        echo ""
        echo "Repository structure:"
        echo "- agents/: Claude Code subagent definitions (10 .md files)"
        echo "- website/: Docusaurus v3 documentation site"
        echo "- .github/workflows/: CI/CD pipelines"
        echo ""
        echo "For website testing, see the 'deploy.yml' and 'ci.yml' workflows"
        exit 0