name: Validate Nephio-O-RAN Agents
on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: pip install pyyaml
    - name: Validate agent structure
      run: |
        chmod +x tests/validate_agents.sh
        ./tests/validate_agents.sh
    - name: Run agent scenario tests
      run: python3 tests/test_agent_scenarios.py
    - name: Test token efficiency monitoring
      run: python3 tests/token_efficiency_monitor.py
