apiVersion: apps/v1
kind: Deployment
metadata:
  name: oran-cu
  namespace: oran-network-functions
  labels:
    app: oran-cu
    component: central-unit
    version: v1.0.0
    nephio.org/deployment-pattern: primary
    nephio.org/version: r5
    security.nephio.org/validation: required
  annotations:
    nephio.org/deployment-type: network-function
    security.nephio.org/l-release-compliant: "true"
    deployment.kubernetes.io/revision: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oran-cu
  template:
    metadata:
      labels:
        app: oran-cu
        component: central-unit
        version: v1.0.0
        sidecar.istio.io/inject: "true"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
        traffic.sidecar.istio.io/includeInboundPorts: "38472,38465,38412,9090"
        sidecar.istio.io/proxyCPU: "100m"
        sidecar.istio.io/proxyMemory: "128Mi"
    spec:
      serviceAccountName: oran-cu-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: oran-cu
        image: oran/cu:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: f1-interface
          containerPort: 38472
          protocol: TCP
        - name: e1-interface
          containerPort: 38465
          protocol: TCP
        - name: ngap-interface
          containerPort: 38412
          protocol: TCP
        - name: metrics
          containerPort: 9090
          protocol: TCP
        env:
        - name: CU_CONFIG_PATH
          value: "/config/cu-config.json"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: JAEGER_AGENT_HOST
          value: "jaeger-agent.istio-system.svc.cluster.local"
        - name: JAEGER_AGENT_PORT
          value: "6831"
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
        - name: certs
          mountPath: /certs
          readOnly: true
        - name: tmp
          mountPath: /tmp
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
      volumes:
      - name: config
        configMap:
          name: oran-cu-config
          defaultMode: 0644
      - name: certs
        secret:
          secretName: oran-cu-certs
          defaultMode: 0400
      - name: tmp
        emptyDir:
          sizeLimit: "100Mi"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: oran-cu
              topologyKey: kubernetes.io/hostname
      tolerations:
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 300
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 300
      terminationGracePeriodSeconds: 60
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: oran-cu-service
  namespace: oran-network-functions
  labels:
    app: oran-cu
    component: central-unit
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - name: f1-interface
    port: 38472
    targetPort: 38472
    protocol: TCP
  - name: e1-interface
    port: 38465
    targetPort: 38465
    protocol: TCP
  - name: ngap-interface
    port: 38412
    targetPort: 38412
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  selector:
    app: oran-cu
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oran-cu-sa
  namespace: oran-network-functions
  labels:
    app: oran-cu
    component: central-unit
  annotations:
    nephio.org/service-account: "network-function"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oran-cu-config
  namespace: oran-network-functions
  labels:
    app: oran-cu
    component: central-unit
data:
  cu-config.json: |
    {
      "id": "cu-001",
      "name": "O-RAN-CU-001",
      "f1_interface": {
        "port": 38472,
        "version": "16.4.0",
        "max_connections": 100
      },
      "e1_interface": {
        "port": 38465,
        "cpup_split": true,
        "bearer_setup": true
      },
      "ngap_interface": {
        "port": 38412,
        "core_endpoints": [
          "amf-service:8080",
          "smf-service:8080",
          "upf-service:8080"
        ],
        "plmn_id": "00101",
        "nr_cgi": "001010000000001"
      },
      "rrc_config": {
        "version": "16.4.0",
        "max_ues": 1000,
        "connection_setup": true,
        "security_enabled": true
      },
      "metrics": {
        "enabled": true,
        "port": 9090,
        "endpoint": "/metrics",
        "interval": 30
      },
      "security": {
        "tls_enabled": true,
        "cert_path": "/certs/cu-cert.pem",
        "key_path": "/certs/cu-key.pem",
        "ca_cert_path": "/certs/ca-cert.pem",
        "mutual_tls": true,
        "jwt_validation": true
      },
      "service_mesh": {
        "istio_enabled": true,
        "tracing_enabled": true,
        "metrics_enabled": true,
        "circuit_breaker": "enabled"
      }
    }
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: oran-cu-vs
  namespace: oran-network-functions
  labels:
    app: oran-cu
    component: central-unit
spec:
  hosts:
  - oran-cu-service
  http:
  - match:
    - headers:
        content-type:
          exact: application/json
    route:
    - destination:
        host: oran-cu-service
        port:
          number: 38472
    timeout: 30s
    retries:
      attempts: 3
      perTryTimeout: 10s
  - route:
    - destination:
        host: oran-cu-service
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: oran-cu-dr
  namespace: oran-network-functions
  labels:
    app: oran-cu
    component: central-unit
spec:
  host: oran-cu-service
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    connectionPool:
      tcp:
        maxConnections: 100
        connectTimeout: 30s
      http:
        http1MaxPendingRequests: 50
        maxRequestsPerConnection: 10
        maxRetries: 3
        consecutiveGatewayErrors: 5
        interval: 30s
        baseEjectionTime: 30s
        maxEjectionPercent: 50
    circuitBreaker:
      consecutiveGatewayErrors: 5
      interval: 30s
      baseEjectionTime: 30s
      maxEjectionPercent: 50
      minHealthPercent: 30
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: oran-cu-pa
  namespace: oran-network-functions
  labels:
    app: oran-cu
    component: central-unit
spec:
  selector:
    matchLabels:
      app: oran-cu
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: oran-cu-authz
  namespace: oran-network-functions
  labels:
    app: oran-cu
    component: central-unit
spec:
  selector:
    matchLabels:
      app: oran-cu
  rules:
  - from:
    - source:
        namespaces: ["oran-network-functions", "istio-system", "monitoring"]
  - to:
    - operation:
        methods: ["GET", "POST", "PUT", "DELETE"]
        paths: ["/f1ap/*", "/e1ap/*", "/ngap/*", "/metrics", "/health"]
---
apiVersion: v1
kind: Secret
metadata:
  name: oran-cu-certs
  namespace: oran-network-functions
  labels:
    app: oran-cu
    component: central-unit
type: kubernetes.io/tls
data:
  # Base64 encoded certificate and key (placeholder)
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCi4uLgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCi4uLgotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0t
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCi4uLgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t