apiVersion: apps/v1
kind: Deployment
metadata:
  name: a1mediator
  namespace: near-rt-ric
spec:
  replicas: 2
  selector:
    matchLabels:
      app: a1mediator
  template:
    metadata:
      labels:
        app: a1mediator
    spec:
      containers:
      - name: a1mediator
        image: o-ran-sc/ric-plt-a1:2.0.0
        ports:
        - containerPort: 10000
          name: http
        env:
        - name: A1_INTERFACE_VERSION
          value: "2.0"
        - name: POLICY_ENGINE_URL
          value: "http://policy-engine:8080"
